package com.aiagent.compiler

import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.symbol.KSFile

/**
 * 把解析后的 [ParsedTool] / [ParsedSkill] 写成单一 .kt 源文件:
 *  - 每个 tool 一个 `class XxxAiTool : Tool`,放在 `com.aiagent.generated.tools`;
 *  - 一个顶层 `fun bootAiTools_<bootName>()`,业务方通过 AiAgentRuntime.install 的
 *    `kspBootstraps` 列入,装机时统一回调一次。
 *
 * 把所有产物塞同一个文件、同一个包,省掉跨文件 `internal` / import 的麻烦,
 * 也方便用户出问题时直接打开 build/generated 里看一眼实际生成内容。
 */
internal class SourceWriter(
    private val env: SymbolProcessorEnvironment,
    private val bootName: String,
) {

    fun write(tools: List<ParsedTool>, skills: List<ParsedSkill>, sources: Set<KSFile>) {
        if (tools.isEmpty() && skills.isEmpty()) return

        val pkg = "com.aiagent.generated"
        val fileName = "AiToolsBoot_${sanitize(bootName)}"

        val out = env.codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = true, *sources.toTypedArray()),
            packageName = pkg,
            fileName = fileName,
        )
        out.bufferedWriter(Charsets.UTF_8).use { w ->
            w.write("// Generated by lib_ai_compiler. DO NOT EDIT.\n")
            w.write("package $pkg\n\n")
            w.write("import com.aiagent.runtime.AiCapabilityRegistry\n")
            w.write("import com.aiagent.runtime.SkillManifest\n")
            w.write("import com.aiagent.runtime.Tool\n")
            w.write("import com.aiagent.runtime.ToolResult\n")
            w.write("import org.json.JSONObject\n\n")
            tools.forEach { writeToolClass(w, it) }
            writeBootFunction(w, tools, skills)
        }
    }

    private fun writeToolClass(w: java.io.Writer, t: ParsedTool) {
        val cls = toolClassName(t.toolName)
        val schema = SchemaWriter.build(t)
        w.write("internal class $cls : Tool {\n")
        w.write("    override val name: String = ${quote(t.toolName)}\n")
        w.write("    override val description: String = ${quote(t.description)}\n")
        w.write("    override val parametersJsonSchema: String = ${quote(schema)}\n")
        w.write("    override val requiresConfirmation: Boolean = ${t.requiresConfirmation}\n")
        w.write("    override val category: String = ${quote(t.category)}\n")
        w.write("    override suspend fun execute(args: JSONObject): ToolResult {\n")
        w.write("        return try {\n")
        ExecuteBodyWriter.write(w, t, indent = "            ")
        w.write("        } catch (t: Throwable) {\n")
        w.write("            ToolResult.Failure(${quote(t.toolName)} + \" failed: \" + (t.message ?: t.javaClass.simpleName))\n")
        w.write("        }\n")
        w.write("    }\n")
        w.write("}\n\n")
    }

    private fun writeBootFunction(w: java.io.Writer, tools: List<ParsedTool>, skills: List<ParsedSkill>) {
        val fnName = "bootAiTools_${sanitize(bootName)}"
        w.write("/**\n")
        w.write(" * 业务方把本函数引用列入 AiAgentRuntime.install 的 kspBootstraps,装机时统一回调。\n")
        w.write(" * 重复调用会因 AiCapabilityRegistry 的去重逻辑抛出 IllegalStateException。\n")
        w.write(" */\n")
        w.write("fun $fnName() {\n")
        tools.forEach { t ->
            w.write("    AiCapabilityRegistry.register(${toolClassName(t.toolName)}())\n")
        }
        skills.forEach { s ->
            w.write("    AiCapabilityRegistry.registerSkill(\n")
            w.write("        SkillManifest(\n")
            w.write("            id = ${quote(s.id)},\n")
            w.write("            name = ${quote(s.name)},\n")
            w.write("            description = ${quote(s.description)},\n")
            w.write("            toolNames = setOf(${s.toolNames.joinToString(", ") { quote(it) }}),\n")
            w.write("        )\n")
            w.write("    )\n")
        }
        w.write("}\n")
    }

    companion object {
        /** snake_case → PascalCase + "AiTool" 后缀。 */
        internal fun toolClassName(toolName: String): String {
            val pascal = toolName.split('_').joinToString("") { part ->
                if (part.isEmpty()) "" else part[0].uppercaseChar() + part.substring(1)
            }
            return "${pascal}AiTool"
        }

        /** 把任意字符串变成合法标识符片段(只留字母数字下划线)。 */
        internal fun sanitize(raw: String): String {
            val sb = StringBuilder(raw.length)
            for (c in raw) {
                sb.append(if (c.isLetterOrDigit() || c == '_') c else '_')
            }
            val s = sb.toString()
            return if (s.isNotEmpty() && s[0].isDigit()) "_$s" else s
        }

        /** 写成 Kotlin 字符串字面量,转义反斜杠和双引号。 */
        internal fun quote(s: String): String {
            val sb = StringBuilder(s.length + 2)
            sb.append('"')
            for (c in s) {
                when (c) {
                    '\\' -> sb.append("\\\\")
                    '"' -> sb.append("\\\"")
                    '\n' -> sb.append("\\n")
                    '\r' -> sb.append("\\r")
                    '\t' -> sb.append("\\t")
                    '$' -> sb.append("\\$")
                    else -> sb.append(c)
                }
            }
            sb.append('"')
            return sb.toString()
        }
    }
}
